### ISSUE TITLE
Fails on Julia master due to racy code

### ISSUE THREAD

**Issue by KristofferC** [christopher-dG/TTLCache.jl#2]
Testing package for upcoming 1.4 this package seems to fail:

```jl
Basic expiry: Test Failed at /Users/kristoffer/JuliaPkgEval/TimeToLive.jl/test/runtests.jl:21
  Expression: isempty(t)
   Evaluated: isempty(TTL{Any,Any}(0 => "!"))

```

Looking a bit at the code, I don't really see how it is guaranteed that the `delete_later` task is executed. Nothing is `wait`ing on it etc so if the scheduler doesn't yield to it, it will not run. 

Running the tests with something like

```jl
function sleep_tics(p)
    for i in 1:100
        sleep(p ÷ 100)
    end
end
```

would make it more likely that the `delte_later` task runs but it is still racy.

**Comment by christopher-dG** [comment]
Thanks for the report, fixed now.
